name = "neuron"
uuid = "bcb0ae3a-089d-4139-844f-006c0eef4fd7"
authors = ["D.L.C. <71894595+semi-dlc@users.noreply.github.com>"]
version = "0.1.0"

[deps]
BifurcationKit = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
DifferentialEquations = "7.16.0"
ForwardDiff = "0.10.38"
LinearAlgebra = "1.11.0"
Pluto = "0.20.4"
PlutoUI = "0.7.23"
Revise = "3.7.2"
SparseArrays = "1.11.0"
