name = "neuron"
uuid = "bcb0ae3a-089d-4139-844f-006c0eef4fd7"
authors = ["D.L.C. <71894595+semi-dlc@users.noreply.github.com>"]
version = "0.1.0"

[deps]
BifurcationKit = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Dates = "1.11.0"
DifferentialEquations = "7.16.0"
ForwardDiff = "0.10.38"
Glob = "1.3.1"
JSON3 = "1.14.3"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
NPZ = "0.4.3"
NonlinearSolve = "4.9.0"
Pluto = "0.20.4"
PlutoUI = "0.7.23"
PyCall = "1.96.4"
PyPlot = "2.11.6"
Revise = "3.7.2"
SparseArrays = "1.11.0"
StatsBase = "0.34.5"
